### ISSUE TITLE
The Filter Section Does Not Use Filter

### ISSUE THREAD

**Issue by tjcarney89** [learn-co-curriculum/map-filter-lab-python#1]
This lab was supposed to deal with Map and Filter and while the Map section is fine, the Filter section seems to be repeated from a previous lab (I believe a looping/conditionals functions lab). Even the summary says so: "Great! Through this lab we saw how to pass arguments to functions, multiple arguments to functions, and how to implement functinons with default arguments."

**Comment by tkoar** [comment]
Lab has been updated with more examples on filter and the appropriate summary. Thanks!
