### ISSUE TITLE
lamentably no lambda

### ISSUE THREAD

**Issue by annieeby** [learn-co-curriculum/map-filter-lab-python#11]
This lab  is supposed to apply and combine the skills covered for map, filter and lambda functions, but I do not believe there has been a lesson on lambda.

Moreover, it instructs to run the first line of code:

from restaurants import yelp_restaurants # in this line we are simply importing our data we gathered from Yelp.

But we do not have a data file yelp_restaurants to import.

**Comment by mas16** [comment]
Hi annieeby, thank you for the feedback. We have updated this lab to include an introduction to lambda. The restaurants.py file contains yelp_restaurants and can be found in the repo. Thanks again!
