### ISSUE TITLE
Lambda is never explained

### ISSUE THREAD

**Issue by timsennett** [learn-co-curriculum/map-filter-lab-python#12]
The lab begins by saying, "In this lab, we'll put our new knowledge about map, filter and lambda functions to the test." But, lambda has not even been mentioned up to this point. I'll do my best to be resourceful, and learn lambda somewhere else, but I think it should have been explained prior to being made necessary in a lab exercise, especially one that is critical to my Data Science technical application.

**Comment by mas16** [comment]
Hi timsennett, thank you for the feedback. We have updated this lab to include an introduction to lambda.
